# Disease.create!(name:"Attention deficit hyperactivity disorder", symptoms:"Gives no close attention to details, Has trouble focusing on tasks even when trying very hard to, Has trouble organizing even simple tasks, Loses things necessary for tasks, Appears forgetful in daily activities, Has a short attention span and being easily distracted, Makes careless mistakes – for example, in schoolwork, Is unable to stick at tasks that are tedious or time-consuming, Appears unable to listen to or carry out instructions, Is constantly changing activity or task, Unable to sit still, Fidgets, Takes risks with little thought for the dangers, Talks excessively, Blurts out answers too early, Has trouble waiting their turn, Interrupts or intrudes on conversations, Says things seemingly unrelated to task/topic.", description:"ADHD is a mental disorder of the neurodevelopmental type. It is characterized by problems paying attention, excessive activity, or difficulty controlling behavior which is not appropriate for a person's age. The symptoms appear before a person is twelve years old, are present for more than six months, and cause problems in at least two settings (such as school, home, or recreational activities).")

# BrainDisease.create!(brain_area_id:2, disease_id:1)

# Disease.create!(name:"Homonymous Hemianopsia", symptoms:"Bumping into or failing to notice things on the side of the hemianopsia. This can make such everyday tasks as crossing the street or driving a car unsafe. Missing parts of words or parts of an eye chart on the side of the hemianopsia when reading. Not noticing objects on a desk or table, or even food on a plate to the side of the hemianopsia. Frustration with reading because it is difficult for the eyes to pick up the beginning of the next line. Tendency to turn the head or body away from the side of the hemianopsia. Drifting in a direction away from the hemianopsia when walking. Visual hallucinations that appear in the form of lights, shapes, or geometric figures or as the image of a recognizable object. Sometimes a movement noted on the normal side of vision is believed to be also seen at the same time on the side of the visual loss.", description:"Hemianopsia or hemianopia is a visual field loss on the left or right side of the vertical midline.Homonymous hemianopsia occurs because the right half of the brain has visual pathways for the left hemifield of both eyes, and the left half of the brain has visual pathways for the right hemifield of both eyes. When one of these pathways is damaged, the corresponding visual field is lost.")

# BrainDisease.create!(brain_area_id:4, disease_id:4)

# Article.create!(name:"Consensus Paper: The Cerebellum's Role in Movement and Cognition", link:"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4089997/", brain_area_id:5)

# Disease.create!(name:"Ataxia", symptoms:"Poor coordination, Unsteady walk and a tendency to stumble, Difficulty with fine motor tasks, such as eating, writing or buttoning a shirt, Change in speech, Involuntary back-and-forth eye movements (nystagmus), Difficulty swallowing", description:"Ataxia describes a lack of muscle control or coordination of voluntary movements, such as walking or picking up objects. A sign of an underlying condition, ataxia can affect various movements, creating difficulties with speech, eye movement and swallowing.")

# BrainDisease.create!(brain_area_id:5, disease_id:5)
